var settings = {
  options: {
    backgroundType: "video",
    backgroundOverlayOpacity: "0",
    backgroundBlur: "0",
    backgroundScale: 1,
    displayBranding: "yes",
    logoOpacity: "0.25",
    logoScale: 1,
    frameWidth: 20,
    sceneTitle:"Gracias por estar aquí hoy.",
    tagline: "Por ahí nos vemos.",
  },
  colors: {
    backgroundOverlay: "rgba(54, 53, 58, 1)",
    accentColor: "rgba(92,0,0,1)",
    frameColor: "rgba(92,0,0,1)",
    primaryTextColor: "rgba(255, 255, 255, 1)",
    subTextColor: "rgba(201,201,201,1)",
    contentBackgrounds: "rgba(255, 255, 255, .1)",
  },
  labels: {
    displayLabels: "no",
    labelOneHeading: "¡Suscriptor más reciente!",
    labelOnePath: "most_recent_subscriber",
    labelTwoHeading: "¡Donación más copada!",
    labelTwoPath: "monthly_top_donator",
    labelThreeHeading: "¡Donación más reciente!",
    labelThreePath: "most_recent_donator",
    labelFourHeading: "¡Nuevo seguidor!",
    labelFourPath: "most_recent_follower",
  },
  schedule: {
    displaySchedule: "no",
    sunday: "3:00pm - 5:00pm",
    monday: "3:00pm - 5:00pm",
    tuesday: "3:00pm - 5:00pm",
    wednesday: "3:00pm - 5:00pm",
    thursday: "3:00pm - 5:00pm",
    friday: "3:00pm - 5:00pm",
    saturday: "3:00pm - 5:00pm",
  },
  scaling: {
    socialMediaScale: "1.5",
    labelsScale: "1.1",
    scheduleScale: "1.5",
    countdownScale: "1.5",
  },
  fonts: {
    primaryFont: "Actor",
    subFont: "Aldrich",
    titleSize: 124,
    titleVerticalOffset: "-4",
    subtitleSize: 32,
    subtitleVerticalOffset: 0,
    labelNameSize: 20,
    labelNameVerticalOffset: "0",
    labelHeaderSize: 12,
    labelHeaderVerticalOffset: "4",
    countdownTimeSize: 60,
    countdownTimeVerticalOffset: 0,
    countdownMessageSize: 24,
    countdownMessageVerticalOffset: 0,
    countdownEndMessageSize: 60,
    countdownEndMessageVerticalOffset: 0,
  },
  countdown: {
    displayCountdown: "yes",
    countdownTime: "1",
    countdownMessage: "Y nos vamos.",
    countdownOverMessage: "Fue un placer.",
  },
  social: {
    displaySocial: "yes",
    twitch: "byUwUr",
    twitterHeader: "Twitter por si mi opinión te interesa.",
    twitter: "@byUwUr",
    facebookHeader: "Facebook por si lo que subo te interesa.",
    facebook: "@byUwUr",
    instagramHeader: "Instagram por si mis fotos te interesan.",
    instagram: "@byUwUr",
    youtubeHeader: "En YouTube sí hago cosas interesantes.",
    youtube: "[Mateus] byUwUr",
  },
};
